version: '3.9'
networks:
  default:
    external: true
    name: bcms
services:
  ui:
    build:
      context: ''
      dockerfile: Dockerfile.dev
    ports:
      - '1281:1281'
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./tailwind.config.cjs
        target: /app/tailwind.config.cjs
      # - type: bind
      #   source: ./node_modules/@tiptap/extension-collaboration-cursor/node_modules/y-prosemirror/src/plugins/cursor-plugin.js
      #   target: /app/node_modules/@tiptap/extension-collaboration-cursor/node_modules/y-prosemirror/src/plugins/cursor-plugin.js
