version: '3.9'
services:
  shim:
    hostname: bcms-shim
    container_name: bcms-shim
    image: 'becomes/cms-shim-local:1.0.5'
  backend:
    hostname: bcms-backend
    container_name: bcms-backend
    depends_on:
      - shim
    image: 'becomes/cms-backend-local:1.0.36'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./shim.json
        target: /app/shim.json
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
  ui:
    hostname: bcms-ui
    container_name: bcms-ui
    build:
      context: ''
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./tailwind.config.cjs
        target: /app/tailwind.config.cjs
      - type: bind
        source: ./postcss.config.cjs
        target: /app/postcss.config.cjs
      - type: bind
        source: ./vite.config.ts
        target: /app/vite.config.ts
  proxy:
    depends_on:
      - ui
      - backend
      - shim
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
