version: '3.9'
services:
  ui:
    build: .
    ports:
      - '5000:5000'
      - '35729:35729'
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
