version: '3.9'
services:
  cms_proxy_v2:
      build: proxy
      ports:
        - "8080:8080"
  cms_ui_v2:
    depends_on:
      - cms_proxy_v2
    build: .
    ports:
      - '5000:5000'
      - '35729:35729'
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
