version: '3.9'
services:
  proxy:
    image: 'becomes/cms-proxy-local'
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
      - '35729:35729'
    logging:
      driver: none
  shim:
    image: 'becomes/cms-shim-local'
    ports:
      - '1282:1282'
    logging:
      driver: none
  backend:
    image: 'becomes/cms-backend-local'
    ports:
      - '1280:1280'
    logging:
      driver: none
    volumes:
      - type: bind
        source: ./bcms.db.json
        target: /app/bcms.db.json
      - type: bind
        source: ./uploads
        target: /app/uploads
    environment:
      - API_PORT=1280
      - DB_PRFX=bcms
      - DB_USE_FS=true
      - JWT_ISSUER=localhost
      - JWT_SECRET=secret
      - JWT_EXP_AFTER=30000000
      - BCMS_LOCAL=true
      - BCMS_INSTANCE_ID=604f489af0db82500f17076d
  ui:
    build: .
    ports:
      - '1281:1281'
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
