version: '3.9'
services:
  proxy:
      build: proxy
      ports:
        - "8080:8080"
  ui:
    depends_on:
      - proxy
    build: .
    ports:
      - '5000:5000'
      - '35729:35729'
    volumes:
      - type: bind
        source: ./public
        target: /app/public
      - type: bind
        source: ./src
        target: /app/src
