export default {
  settingsSideMenuItem: '[data-cy=settings] > .sideNav--section-toggler',
  languages: '[data-cy=settings] > :nth-child(2) > :nth-child(1)',
  addLanguage: '[data-cy=add]',
  searchLanguage: '._bcmsInput--select-search-input',
  selectLanguageFromSearch: '._bcmsInput--select-list-item',
  confirmLanguageDelete: '.bcmsButton_primary',
  addMember: '.managerLayout--sideNav--footer-inner > .bcmsButton',
  email: '#Email',
  firstName: '#First\\ name',
  lastName: '#Last\\ name',
  password: '#New\\ password',
  allowAllPermissions: '.crud-policy--options > .bcmsButton',
  update: '.um--actionButtons > .bcmsButton_primary',
  deleteMember: '.bcmsButton_danger',
  addNewKey: '.bcmsButton',
  enterKeyLabel: '#Label',
  enterKeyDescription: '.CodeMirror-lines',
  deleteKey: '[data-cy=delete-policy]',
  entries: '[data-cy=entries]',
  promoteToAdmin: '.bcmsButton_secondary',
  confirmActionInModal: '.bcmsModal--actions > .bcmsButton_primary'
}
