export default {
  entries: '[data-cy=entries]',
  addNewEntry: '[data-cy=add-new]',
  save: '[data-cy=add-update]',
  title: '.ql-editor',
  addNewDirector: '.entryEditor--prop_ARRAY-wrapper > .bcmsButton',
  directorSelectBox: '#bcmsSelect_button',
  secondDirectorSelectBox: ':nth-child(2) > .entryEditor--prop_ARRAY_ITEM-content > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--select',
  deleteFirstDirector: ':nth-child(1) > .entryEditor--prop-header > .entryEditor--prop-header-inner > .entryEditor--prop-header-actions > :nth-child(2) > svg',
  firstDirector: ':nth-child(1) > .entryEditor--prop_ARRAY_ITEM-content > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--select > #bcmsSelect_button > span',
  secondDirector: ':nth-child(2) > .entryEditor--prop_ARRAY_ITEM-content > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--select > #bcmsSelect_button > span',
  secondDirectorSection: '.entryEditor--prop_ARRAY-inner > :nth-child(2)',
  swapPositions: ':nth-child(2) > .entryEditor--prop-header > .entryEditor--prop-header-inner > .entryEditor--prop-header-actions > :nth-child(1) > svg',
  streetAddress: ':nth-child(1) > [data-cy=prop-string] > .entryEditor--prop-body > .prop--string > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--textarea',
  streetAddress2: ':nth-child(2) > [data-cy=prop-string] > .entryEditor--prop-body > .prop--string > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--textarea',
  city: ':nth-child(3) > [data-cy=prop-string] > .entryEditor--prop-body > .prop--string > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--textarea',
  state: ':nth-child(4) > [data-cy=prop-string] > .entryEditor--prop-body > .prop--string > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--textarea',
  country: ':nth-child(5) > [data-cy=prop-string] > .entryEditor--prop-body > .prop--string > ._bcmsInput > ._bcmsInput--inner > ._bcmsInput--textarea',
  secondCompanyName: '[data-cy=item-1] > .entryOverview--entries-title > span',
  firstCompanyName: '[data-cy=item-0] > .entryOverview--entries-title > span',
  edit: '[data-cy=edit] > span',
  optionsMenu: '.overflowMenu--trigger',
  model: '[data-cy=view-model] > button',
  deleteEntry: '[data-cy=remove] > button',
  modalBody: '.bcmsModal--body'
}